import { storage } from "../storage";
import { ComparisonOrchestrator } from "../services/comparisonOrchestrator";
import { db } from "../db";
import { companyComparisons } from "@shared/schema";
import { eq } from "drizzle-orm";

/**
 * QUICK TEST: Verify AI prompt fixes work
 * Tests ONLY Alm. Brand comparison to verify:
 * 1. Coverage rows are preserved (not regenerated by AI)
 * 2. All 3 policies appear in output
 */

const USER_ID = 'e85ec3b9-e354-4c49-9f68-194830e356af';
const ALM_BRAND_COMPANY_ID = 'abd44932-e5b2-4fda-a463-e75fd46c1ccc';

async function main() {
  console.log('==================================================');
  console.log('TEST: Alm. Brand Comparison with AI Prompt Fixes');
  console.log('==================================================\n');

  try {
    // Delete existing comparison for Alm. Brand
    console.log('[Cleanup] Deleting existing Alm. Brand comparison...');
    const deleted = await db
      .delete(companyComparisons)
      .where(eq(companyComparisons.offerCompany, ALM_BRAND_COMPANY_ID));
    console.log(`[Cleanup] Deleted ${deleted.rowCount || 0} comparisons\n`);

    // Run comparison
    const orchestrator = new ComparisonOrchestrator(storage);
    console.log('[Comparison] Running comparison for Alm. Brand...');
    const result = await orchestrator.runForUser({
      userId: USER_ID,
      offerCompany: ALM_BRAND_COMPANY_ID,
      forceRerun: true
    });

    console.log('\n[Result]', JSON.stringify(result, null, 2));

    if (result.comparisonIds.length > 0) {
      const comparisonId = result.comparisonIds[0];
      const [comparison] = await db
        .select()
        .from(companyComparisons)
        .where(eq(companyComparisons.id, comparisonId));

      if (comparison) {
        const policyComparisons = (comparison.comparisonJSON as any)?.policyComparisons || [];
        
        console.log('\n==================================================');
        console.log('VALIDATION RESULTS');
        console.log('==================================================');
        console.log(`Status: ${comparison.status}`);
        console.log(`Policy Count: ${policyComparisons.length} (expected: 3)`);
        
        let allPassed = true;
        for (const policy of policyComparisons) {
          const coverageRows = policy.coverageComparison?.rows || [];
          const rowCount = coverageRows.length;
          const passed = rowCount >= 3;
          const status = passed ? '✅' : '❌';
          
          console.log(`  ${status} ${policy.policyType.padEnd(8)} - ${rowCount} coverage rows ${passed ? '(PASS)' : '(FAIL: need >= 3)'}`);
          
          if (!passed) {
            allPassed = false;
          }
        }
        
        console.log(`\n${allPassed && policyComparisons.length === 3 ? '✅ TEST PASSED' : '❌ TEST FAILED'}`);
        console.log('==================================================\n');
        
        process.exit(allPassed && policyComparisons.length === 3 ? 0 : 1);
      }
    }

    console.error('❌ No comparison created');
    process.exit(1);
  } catch (error) {
    console.error('\n❌ Test failed:', error);
    if (error instanceof Error) {
      console.error(error.stack);
    }
    process.exit(1);
  }
}

main();
